# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# some modules are better than other modules, those that are worst are listed here
submodules:
  exclude:
    - golden_ecat.py
    - tests


# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - cd pypet2bids && poetry lock && poetry install --all-extras
      - cd pypet2bids && poetry build && pip install dist/pypet2bids-*.whl
      - export PATH=$PATH:$PWD/pypet2bids/pypet2bids

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
