name: Collect Data OpenNeuro Posix
on: push
jobs:
  Collect-Data:
    runs-on: ${{ matrix.os }}

    env:
      ECAT_URL: https://openneuro.org/crn/datasets/ds003773/snapshots/1.0.0/files/sourcedata:ecat73:cimbi36.tar.gz

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Collect Ecat Dataset w/ curl
        run: "curl -o ecat_test ${{ env.ECAT_URL }}"

      - name: Decompress dataset
        run: "tar xvzf ecat_test"

      - name: Install Python Reqs
        run: pip3 install -r python/requirements.txt