name: Test On Phantoms
on:
  push:
  workflow_dispatch:
  pull_request:
      branches:
        - main

jobs:
  run_setup_workflow:
    uses: ./.github/workflows/setup_phantoms_and_deps.yaml

  run_conversions:
    runs-on: ${{ matrix.os }}
    needs: run_setup_workflow
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-latest]
        python: ["3.9", "3.10"]

    steps:
      - name: List Directory
        run: ls .

  matlab:
    runs-on: ubuntu-20.04
    needs: run_setup_workflow
    uses: ./.github/workflows/matlab.yaml

  setup_and_cli_test_posix.yaml:
    runs-on: ${{ matrix.os }}
    needs: run_setup_workflow
    uses: ./.github/workflows/setup_and_cli_test_posix.yaml