name: Test On Phantoms
on:
  push:
  workflow_dispatch:
  pull_request:
      branches:
        - main

jobs:
  run_setup_workflow:
    uses: ./.github/workflows/setup_phantoms_and_deps.yaml
    runs-on: ${{ matrix.os }}
    matrix:
      os: [macOS-latest, ubuntu-20.04, windows-latest]
      python: ["3.9", "3.10"]
    fail-fast: false

  run_conversions:
    steps:
      - name: List Directory
        run: ls .
