name: Test On Phantoms
on:
  push:
  pull_request:
      branches:
        - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  run_setup:
    uses: ./.github/workflows/setup.yaml
    secrets: inherit


  run_conversions:
    runs-on: ${{ matrix.os }}
    needs: run_setup
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-latest]
        python: ["3.9", "3.10"]

    steps:

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        timeout-minutes: 15
        with:
          limit-access-to-actor: true

      - name: List Directory
        run: ls .


  matlab:
    needs: run_setup
    uses: ./.github/workflows/matlab.yaml
    secrets: inherit

  setup_and_cli_test_posix:
    needs: run_setup
    uses: ./.github/workflows/setup_and_cli_test_posix.yaml
    secrets: inherit