name: Test On Phantoms
on:
  push:
  workflow_dispatch:
  pull_request:
      branches:
        - main

jobs:
  run_setup:
    uses: ./.github/workflows/setup.yaml
    secrets: inherit

  run_conversions:
    runs-on: ${{ matrix.os }}
    needs: run_setup_workflow
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-latest]
        python: ["3.9", "3.10"]

    steps:
      - name: List Directory
        run: ls .

      - name: Setup Debug Session
        uses: csexton/debugger-action@master

  matlab:
    needs: run_setup_workflow
    uses: ./.github/workflows/matlab.yaml
    secrets: inherit

  setup_and_cli_test_posix:
    needs: run_setup_workflow
    uses: ./.github/workflows/setup_and_cli_test_posix.yaml
    secrets: inherit