name: Test On Phantoms
on:
  push:
  pull_request:
      branches:
        - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  phantoms_test:
    secrets: inherit
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-latest]

    steps:
      - name: SETUP
        uses: ./.github/workflows/setup.yaml

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        timeout-minutes: 15
        with:
          limit-access-to-actor: true

      - name: List Directory
        run: ls .

      - name: matlab
        uses: ./.github/workflows/matlab.yaml
        secrets: inherit

      - name: setup_and_cli_test_posix
        uses: ./.github/workflows/setup_and_cli_test_posix.yaml
        secrets: inherit