name: Windows Get Dcm2niix
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  GetDcm2niix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd pypet2bids
          pip3 install .

      - name: Use CLI to set path to dcm2niix
        run: |
          cd pypet2bids
          python dcm2niix4pet.py --set-dcm2niix-path